### ISSUE TITLE
Saas Cleanup

### ISSUE THREAD

**Issue by Eonasdan** [Eonasdan/tempus-dominus#2370]
The sass file is a bit messy and could use some clean up. There's a couple of hard referenced styles that could use a sass variable instead for instance

- [x] Clean up color references
- [x] Check for syntax optimizations
- [x] Look at how bootstrap 5 provides `--root` styles
- [x] Investigate if it's worth creating a process to extract certain styles from bootstrap to keep the picker styles updated
- [x] Create a dark theme

**Comment by Eonasdan** [comment]
I'm stuck with a css issue I'm not sure what I'm missing.  In v5 I was using Bootstrap 4, in v6 I'm removing the bootstrap dependency but still trying to use the ideas of BS5 styles. v5 had nice spacing around the elements.
![image](https://user-images.githubusercontent.com/1006516/130148771-71b63c79-8407-4a91-9dcd-fb044ab84d59.png)
v6 not so much
![image](https://user-images.githubusercontent.com/1006516/130148790-f19438a7-ffbe-465b-8b98-92b6d92db0ee.png)

Look at the month view it's very sad.
![image](https://user-images.githubusercontent.com/1006516/130148881-d5c96261-0190-40eb-a44c-636bca84218e.png)

I have [a stackblitz](https://stackblitz.com/edit/js-byfw5j?file=index.html) of the compiled code.

I've migrated most of these styles from bs 3 -> bs4 -> trying to not be dependent on bootstrap at all. The css hasn't had a good clean up in a while and frankly I'd be ok burning it all lol. The [dp from Material](https://material.angular.io/components/datepicker/overview) doesn't look bad.

**Comment by Eonasdan** [comment]
Someone pointed me to a css change and it did make some improvements. I decided to look at the material picker again and copied some idea from there. It looks a bit better I think but still some ugliness.

![image](https://user-images.githubusercontent.com/1006516/130165789-2367ddbd-0daf-490e-9bac-7786db495bd4.png)

**Comment by lukasjuhrich** [comment]
What do you mean by „some ugliness“?

I can add some random specifics that come to mind from my personal point of view, if that helps:

1. The numbers from this month vs. the numbers from the adjacent month look almost the same (the contrast is too marginal to make a distinction), there must be a better way of deemphasizing them. However, if the font thickness does not play along, making the color lighter may make them unreadable.
But perhaps that's okay since they only provide supporting information and the content should be clear from the context (e.g. if it's the day before Jul 1 then it must be Jun 30)
2. The focus on the selected date looks a bit weird to me, but I'm not sure why. Perhaps it's the height; it seems like it's forcefully squished which is irritating because there's quite enough space around.
3. (not CSS related) One might want to include the year. It cannot be guaranteed to be clear from the context.

Perhaps an  comparison would be the nextcloud datetime picker (which, judging by the class name, uses `mx-datepicker`):
![image](https://user-images.githubusercontent.com/10060406/130331645-271a5720-713f-4294-bbcb-d9d099d2bd6c.png)

**Comment by Eonasdan** [comment]
I've managed to fix the css bug I was facing. I replaced all the table elements to use CSS Grid instead 
![image](https://user-images.githubusercontent.com/1006516/130370074-2c21f5a1-b962-4dbf-8f10-f9652c2419df.png)
This also fixed the month view
![image](https://user-images.githubusercontent.com/1006516/130370080-2ad5d982-ba87-4005-b99e-27a93376c593.png)
