### ISSUE TITLE
Date format doesn't appear to be used/applied

### ISSUE THREAD

**Issue by nickalbrecht** [Eonasdan/tempus-dominus#2403]
Trying to customize the date control to use a custom format. For example to get a date to look like "Sept 15, 2021". However, after picking the date, it shows as "9/15/2021". Doesn't seem like it's using the custom date format at all. Not entirely sure if I'm using the correct options to specify a format, but I used the documentation as much as possible to get this far.

https://stackblitz.com/edit/js-aqvqwe?file=index.js

**Comment by akbaryahya** [comment]
so this is a bug? in previous version v4 i used like this

`
$('#set_start').datetimepicker({
    format: 'YYYY-MM-DD HH:mm',
    defaultDate: moment().add(-1, 'hours').format('YYYY-MM-DD HH:mm'),
});
`

in latest version (v6) it doesn't work even when trying code something like

`
new tempusDominus.TempusDominus(document.getElementById('set_start'), {
    //format: 'YYYY-MM-DD HH:mm',
    display: {
        inputFormat: 'YYYY-MM-DD HH:mm'
    },
    //defaultDate: moment().format('YYYY-MM-DD HH:mm'),
});
`

I'm confused

**Comment by nickalbrecht** [comment]
There's an issue somewhere in there too. I have no options set for the following explanation. If I type into the field `Sept 1, 2021`, and hit <kbd>tab</kbd>, it gets rewritten as `09/01/2021, 12:00 AM`. If I then delete the text in the input box, and type `Sept 1, 2021` in again, then hit <kbd>tab</kbd>, nothing happens. it stays as I entered it.

**Comment by Eonasdan** [comment]
I could add a check internally for an empty value, but I would think it would be up to the function to check that first and return an empty string. Otherwise, if you wanted to force a value on empty.. I guess you could listen to the change function.

For you second issue, I think is because I provide a basic input format based on the selected components and then use Intl to format the date. E.g. [`Intl.DateTimeFormat('default', clickmeFormat).format(new Date('Sept 1, 2021'))` ](https://github.com/Eonasdan/tempus-dominus/blob/master/src/js/tempus-dominus.ts#L329)

**Comment by nickalbrecht** [comment]
I think you're right, that makes sense that it'd up to the implementation of `inputFormat` to determine how to handle `null`s.

**Comment by Eonasdan** [comment]
Hello. Please check the preview branch again. That stackblitz should still work, though you might have to clear your cache.

Originally there was code to ignore the change if the dates evaluated to the same. I've changed this a bit so it will still update the input field regardless.
