### ISSUE TITLE
Wrong calendar rendering when startOfTheWeek: 1

### ISSUE THREAD

**Issue by K4kTyC** [Eonasdan/tempus-dominus#2473]
Wrong calendar rendering when **startOfTheWeek: 1** or anything other than 0, I guess.

For example, for May 2022. Calendar starts from May 2:
![изображение](https://user-images.githubusercontent.com/47088033/150702557-6a234795-0ab0-4a90-b36c-71216441a554.png)

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-37wmqw?file=index.js

Version: 6.0.0-beta1

**Comment by William-H-M** [comment]
Uhh works fine for me, maybe a cache issue?
![imagen](https://user-images.githubusercontent.com/24443241/151095960-24bed41f-6b30-4f0f-8050-30ed29b972be.png)

**Comment by K4kTyC** [comment]
I guess you've checked March, not May :)

**Comment by Eonasdan** [comment]
Hello, please check the development branch. This should be fixed. You can test it out on [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next).

**Comment by William-H-M** [comment]
I did work for `startOfTheWeek: 1` but not for `2` and `3`, so doing some testing I did this horror on the lane changed and worked:

```
if (startOfTheWeek !== 0 && this.weekDay === 0) {
  goBack = (7 + startOfTheWeek) - startOfTheWeek;
}
``` 

Which is pretty much simplified to `goBack = 7`

This works for up to `startOfTheWeek = 3` because after that `this.weekDay` is not 0 anymore, and it becomes funny.

### May with `startOfTheWeek: 1`
![imagen](https://user-images.githubusercontent.com/24443241/153329834-b3e71787-b155-45c6-9fc2-e3d6ba10abbd.png)

### May with `startOfTheWeek: 2` and using windows calendar to confirm
![imagen](https://user-images.githubusercontent.com/24443241/153329984-76d64f9a-250d-4390-9064-3abba196a6d8.png)

### May with `startOfTheWeek: 3`
![imagen](https://user-images.githubusercontent.com/24443241/153330127-accf6e34-93bc-4b49-9ca6-3a6b75fea143.png)

To be fair using `startOfTheWeek: 3` seems a pretty extreme use case, but it works, kinda

**Comment by K4kTyC** [comment]
Works fine on stackblitz, thank you
