### ISSUE TITLE
Jump to the next month with the first day is skipping a month

### ISSUE THREAD

**Issue by nandicrisan** [Eonasdan/tempus-dominus#2474]
1. Open the picker  then select 01/31/2022 (MM/DD/YYYY)
2. Select the first date from the next month
3. The selected date should be 02/01/2022
Result:
The selected date is 03/01/2022

![image](https://user-images.githubusercontent.com/6093662/150842692-a48917f5-e0e4-43db-a878-66c7cd0d90d5.png)
|
![image](https://user-images.githubusercontent.com/6093662/150842802-36848ed3-9bd5-4036-9925-869b9a945af1.png)

System

- Operating system: Windows 11
- Browser and version:  Opera 82.0.4227.58
- Version of the plugin: Tempus dominus  6.0.0-beta2

**Comment by William-H-M** [comment]
I confirm the bug and add another one, and if an image a thousand words, a video is best.

It happens because of the overflow on a change of month, triggered on the [`manipulate`](https://github.com/Eonasdan/tempus-dominus/blob/master/src/js/datetime.ts) method.

Maybe we would need a check of the month that have less than 31 days to avoid this, and manipulate to their max day?

https://user-images.githubusercontent.com/24443241/151098371-6aef2722-9e0f-4f5c-a787-9d0e274acf0d.mp4

**Comment by Eonasdan** [comment]
Hello, please check the development branch. This should be fixed. You can test it out on [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next).

**Comment by William-H-M** [comment]
Confirm fixed, no problems that jump to the view

https://user-images.githubusercontent.com/24443241/153110456-e1f346db-71ed-4bd7-8fc5-13f5004609a4.mp4

**Comment by josephcrowell** [comment]
I confirm that it's fixed as well. Thanks!
