### ISSUE TITLE
v6.7.13 maxDate option crashes the plugin

### ISSUE THREAD

**Issue by johncrislasta** [Eonasdan/tempus-dominus#2850]
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

I have installed v6.7.13 and I'm getting an error when I set the maxDate in the restrictions option.

The error is:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'localization')
    at set viewDate [as viewDate]
```
    
I tested my setup on the stackblitz provided, but it worked:
I discovered that using a lower version, 6.7.7 worked.
I'll just use that version until the issue is fixed on the latest release.

Thanks!

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-cwswbe?file=index.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of are you using? You can find this information from the sample StackBlitz.

6.7.13

### What your browser's locale? You can find this information from the sample StackBlitz.

en-US

**Comment by Gandhi11** [comment]
Same things is happening with the `minDate` restriction.

**Comment by Gandhi11** [comment]
After digging a little bit it look like it is related to the changes done for #2828

**Comment by apircher** [comment]
I have the same problem. The error occurs in the [viewDate setter](https://github.com/Eonasdan/tempus-dominus/blob/93de311d9db5cb861931c16a06568a742413f1a8/src/js/tempus-dominus.ts#L90C13-L90C13) when the viewDate is set from `_initializeOptions` - before `this.optionsStore.options` is assigned.

The setter tries to call `this.optionsStore.viewDate.setLocalization(this.optionsStore.options.localization)` but `this.optionsStore.options` is undefined.

It happens if there is a maxDate and the viewDate (i.e. new Date()) is after the maxDate or if there is a minDate and the viewDate is before the minDate.

**Comment by solomax** [comment]
Also reproducible for me ...
Everything works as expected with `6.7.11`

**Comment by youlead-bow** [comment]
We also have the bug

**Comment by Eonasdan** [comment]
New release should fix this.
